name: Tests

on:
  push:
    branches: 
      -master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run:  vendor/bin/phpunit -c phpunit.xml  
